### ISSUE TITLE
CUDA initialization error

### ISSUE THREAD

**Issue by im281** [MannLabs/alphapept#403]
running multiple files in the **test_gpu.py script** results in a cuda initialization error. A single file can be run but it is not using GPU. 

`
def main():
mode = 'numba-multithread' #'cuda' #sys.argv[1]
print(f"Testing with mode {mode}")
global alphapept
alphapept.performance.set_compilation_mode(mode)
alphapept.performance.set_worker_count(0)
importlib.reload(alphapept.feature_finding)

#delete_folder(tmp_folder)
#create_folder(tmp_folder)

for file in FILE_DICT:
    target = os.path.join(tmp_folder, file)
    if not os.path.isfile(target):
        wget.download(FILE_DICT[file], target)

settings = load_settings(DEFAULT_SETTINGS_PATH)
settings['experiment']['file_paths'] =  [os.path.join(tmp_folder, 'test1.raw')]#,
                                         #os.path.join(tmp_folder, 'test2.raw'),
                                         #os.path.join(tmp_folder, 'test3.raw')]
#settings['experiment']['file_paths'] =  [os.path.join(tmp_folder, 'thermo_IRT.raw')]
settings['experiment']['fasta_paths'] = [os.path.join(tmp_folder, 'IRT_fasta.fasta')]

import alphapept.interface
#settings = load_settings('/home/ubuntu/apps/alphapept/test_settings.yaml')

settings_ = alphapept.interface.import_raw_data(settings)
start = time()
settings_ = alphapept.interface.feature_finding(settings)
end = time()

te = end-start

print(f'Time elapsed {te}')
if name == "main":
main()`

**Comment by im281** [comment]
Running this test code to test CUDA results in the following error:

`import torch

print(torch.cuda.is_available())

import cupy as cp
import numpy as np

x_cpu = np.array([1, 2, 3])
x_gpu = cp.array([1, 2, 3])

l2_cpu = np.linalg.norm(x_cpu)
l2_gpu = cp.linalg.norm(x_gpu)

print("Using Numpy: ", l2_cpu)
print("\nUsing Cupy: ", l2_gpu)


x = cp.array([1, 2, 3])
print(x.device)
print('count: ',cp.cuda.runtime.getDeviceCount())
cp.cuda.Device(1).use()

`






<CUDA Device 0>
count:  1
Traceback (most recent call last):
  File "/home/ubuntu/cuda.py", line 21, in <module>
    cp.cuda.Device(1).use()
  File "cupy/cuda/device.pyx", line 196, in cupy.cuda.device.Device.use
  File "cupy/cuda/device.pyx", line 222, in cupy.cuda.device.Device.use
  File "cupy_backends/cuda/api/runtime.pyx", line 355, in cupy_backends.cuda.api.runtime.setDevice
  File "cupy_backends/cuda/api/runtime.pyx", line 132, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidDevice: invalid device ordinal
