### ISSUE TITLE
FileWatcher setup fails with error AttributeError: module 'streamlit' has no attribute 'script_runner'

### ISSUE THREAD

**Issue by heuselm** [MannLabs/alphapept#460]
**Describe the bug**

FileWatcher setup fails with error AttributeError: module 'streamlit' has no attribute 'script_runner'
Traceback:
File "streamlit\scriptrunner\script_runner.py", line 475, in _run_script
    exec(code, module.__dict__)
File "C:\Program Files (x86)\AlphaPept\alphapept\webui.py", line 46, in <module>
    sidebar[menu]()
File "alphapept\gui\filewatcher.py", line 222, in filewatcher
    raise st.script_runner.RerunException(

**To Reproduce**
1. Go to http://localhost:8505/
2. Click on FileWatcher, configure folder to watch
3. Press start

**Expected behavior**
File watcher to start and files arriving in the watched folder to be added to the processing queue.

**Screenshots**
<img width="955" alt="image" src="https://user-images.githubusercontent.com/8591937/173073932-50c00762-b28f-4c00-9117-3128ecac9d0f.png">

**Version (please complete the following information):**
 - OS: Windows 10 Pro 21H2 19044.1706 Windows Feature Experience Pack 120.2212.4170.0
 - Version 0.4.6 https://github.com/MannLabs/alphapept/releases/download/v0.4.6/AlphaPept-Windows-64bit_v0.4.6.exe
 - Installation Windows One-Click Installer

**Additional context**
- Previous AlphaPept version installed on same System: 0.3.3
- It seems the FileWatcher starts all right and only streamlit fails to run the analysis scripts (Wrong Streamlit version packaged into 1-click installer maybe?)
- No analysis starts after Bruker.d file is moved to watched folder

-------------------------
 Local URL: http://localhost:8505
 Network URL: [removed]

2022-06-10 15:08:09.437 INFO    numexpr.utils: Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-06-10 15:08:09.437 INFO    numexpr.utils: NumExpr defaulting to 8 threads.
2022-06-10 15:08:10.611 INFO    matplotlib.font_manager: generated new fontManager
2022-06-10 15:08:15.656 INFO    root: Using existing settings.
2022-06-10 15:08:15.686 INFO    root: Cupy is not available
2022-06-10 15:08:15.686841 Started queue_watcher
2022-06-10 15:16:47.018 Traceback (most recent call last):
  File "streamlit\scriptrunner\script_runner.py", line 475, in _run_script
    exec(code, module.__dict__)
  File "C:\Program Files (x86)\AlphaPept\alphapept\webui.py", line 46, in <module>
    sidebar[menu]()
  File "alphapept\gui\filewatcher.py", line 222, in filewatcher
    raise st.script_runner.RerunException()
AttributeError: module 'streamlit' has no attribute 'script_runner'

2022-06-10 15:16:47.966 INFO    numexpr.utils: Note: NumExpr detected 64 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-06-10 15:16:47.966 INFO    numexpr.utils: NumExpr defaulting to 8 threads.
2022-06-10 15:16:49.106 INFO    matplotlib.font_manager: generated new fontManager
2022-06-10 15:16:53.886 INFO    root: Using existing settings.
2022-06-10 15:16:53.886314 file watcher started.
---------------------------

**Comment by straussmaximilian** [comment]
Thanks for reporting. The error is indeed caused by a new streamlit version. I will include it in the next version.
Just to confirm: Are no files added to the queue? In principle, the error should not prevent the watcher from starting.
