### ISSUE TITLE
cannot install pythonnet 2.5.2 in linux

### ISSUE THREAD

**Issue by grandrea** [MannLabs/alphapept#545]
Hello,

Running 

    pip install pythonnet==2.5.2

results in TrustFailure/Authentication Failure.

I am within a conda environment in linux Centos 8 64 bit. I have successfully installed alphapept and it "runs" except it does not find results for thermo .raw. I have installed mono via conda-forge (i am not admin) and added it to the path. mono version is 6.12.0.90 . I attach my conda environment.

Installation of pythonnet 3.1 is successful, but that does not help alphapept process thermo files, it seems?

Error trace:

    bash-4.4$ pip install pythonnet==2.5.2
    WARNING: Ignoring invalid distribution -umba (/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages)
    WARNING: Ignoring invalid distribution -umba (/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages)
    Collecting pythonnet==2.5.2
      Downloading pythonnet-2.5.2.tar.gz (1.9 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 14.1 MB/s eta 0:00:00
      Preparing metadata (setup.py) ... done
    Requirement already satisfied: pycparser in ./miniconda3/envs/pept/lib/python3.8/site-packages (from pythonnet==2.5.2) (2.21)
    Building wheels for collected packages: pythonnet
      Building wheel for pythonnet (setup.py) ... error
      error: subprocess-exited-with-error
      
      × python setup.py bdist_wheel did not run successfully.
      │ exit code: 1
      ╰─> [56 lines of output]
          running bdist_wheel
          running build
          running build_ext
          Checking for updates from https://www.nuget.org/api/v2/.
          Error: TrustFailure (Authentication failed, see inner exception.)
            Authentication failed, see inner exception.
            Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
              at /home/conda/feedstock_root/build_artifacts/mono_1614918204952/work/external/boringssl/ssl/handshake_client.c:1132
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/tmp/pip-install-jksfkkte/pythonnet_2649fa1ce8614f9c9f2ebee59b50e1de/setup.py", line 630, in <module>
              setup(
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
              return distutils.core.setup(**attrs)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
              return run_commands(dist)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
              dist.run_commands()
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
              self.run_command(cmd)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
              super().run_command(command)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
              cmd_obj.run()
            File "/tmp/pip-install-jksfkkte/pythonnet_2649fa1ce8614f9c9f2ebee59b50e1de/setup.py", line 612, in run
              return bdist_wheel.bdist_wheel.run(self)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
              self.run_command("build")
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
              self.distribution.run_command(command)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
              super().run_command(command)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
              cmd_obj.run()
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
              self.run_command(cmd_name)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
              self.distribution.run_command(command)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
              super().run_command(command)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
              cmd_obj.run()
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
              self.build_extensions()
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
              self._build_extensions_serial()
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
              self.build_extension(ext)
            File "/tmp/pip-install-jksfkkte/pythonnet_2649fa1ce8614f9c9f2ebee59b50e1de/setup.py", line 249, in build_extension
              self._install_packages()
            File "/tmp/pip-install-jksfkkte/pythonnet_2649fa1ce8614f9c9f2ebee59b50e1de/setup.py", line 438, in _install_packages
              subprocess.check_call(cmd, shell=use_shell)
            File "/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/subprocess.py", line 364, in check_call
              raise CalledProcessError(retcode, cmd)
          subprocess.CalledProcessError: Command 'mono tools/nuget/nuget.exe update -self' returned non-zero exit status 1.
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for pythonnet
      Running setup.py clean for pythonnet
    Failed to build pythonnet
    WARNING: Ignoring invalid distribution -umba (/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages)
    Installing collected packages: pythonnet
      Running setup.py install for pythonnet ... error
      error: subprocess-exited-with-error
      
      × Running setup.py install for pythonnet did not run successfully.
      │ exit code: 1
      ╰─> [6 lines of output]
          usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
             or: setup.py --help [cmd1 cmd2 ...]
             or: setup.py --help-commands
             or: setup.py cmd --help
          
          error: option --single-version-externally-managed not recognized
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: legacy-install-failure
    
    × Encountered error while trying to install package.
    ╰─> pythonnet
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for output from the failure.
    WARNING: Ignoring invalid distribution -umba (/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages)
    WARNING: Ignoring invalid distribution -umba (/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages)
    WARNING: Ignoring invalid distribution -umba (/home/andrea.graziadei/miniconda3/envs/pept/lib/python3.8/site-packages)
    

[pept.txt](https://github.com/MannLabs/alphapept/files/11342702/pept.txt)

**Comment by grandrea** [comment]
For anyone else running into this issue. 

I have managed to solve the problem by installing pythonnet via conda and alphapept now runs fine from thermo .raw
    conda install -c conda-forge pythonnet==2.5.2
