### ISSUE TITLE
Task failed

### ISSUE THREAD

**Issue by cksakura** [MannLabs/alphapept#556]
Please see the following information:

> An exception occured running AlphaPept version 0.5.1:

....................................................

can only concatenate str (not "int") to str

2023-12-01 12:07:29> Traceback
Traceback (most recent call last):
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\alphapept\__main__.py", line 12, in main
    alphapept.interface.run_cli()
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\alphapept\interface.py", line 1409, in run_cli
    cli_overview()
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\alphapept\interface.py", line 1560, in cli_workflow
    run_complete_workflow(settings, progress = progress)
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\alphapept\interface.py", line 1014, in run_complete_workflow
    settings = step(settings, logger_set = True,  settings_parsed = True, callback = cb)
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\alphapept\interface.py", line 786, in quantification
    m.columns = [col_ +_ for _ in m.columns]
  File "C:\Users\kchen2\AppData\Local\anaconda3\envs\alphapept\lib\site-packages\alphapept\interface.py", line 786, in <listcomp>
    m.columns = [col_ +_ for _ in m.columns]
TypeError: can only concatenate str (not "int") to str

**Comment by straussmaximilian** [comment]
Hi, could you provide more context what you tried?
Just tried with a fresh install and couldn't find any obvious errors.
Thanks!

**Comment by cksakura** [comment]
Hello, thank you for your response.
Please find the attached files for more information.

[alphapept_result.zip](https://github.com/MannLabs/alphapept/files/13548289/alphapept_result.zip)

**Comment by straussmaximilian** [comment]
Okay it looks like it searched the file and got some 200 proteins.
Did you use the Gui? If so, could you share the logfile?
Could you also share the raw file and the .fasta file so that I can run it and try to reproduce the issue?

**Comment by straussmaximilian** [comment]
Here would be an anonymous upload to share the files:
https://datashare.biochem.mpg.de/s/8LWBwNfX6S8RVK6

From the log it looks like it went through fine but hat had some issues writing the proteins...

**Comment by cksakura** [comment]
Thank you for your help. I have uploaded one raw file and the database. Maybe the problem is about the protein inference. Because it's a microbiome database, a peptide could be mapped to hundreds of proteins.
